### ISSUE TITLE
Latest release breaking website CI

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon-charts#363]
@alisonjoseph @theiliad I think something went wrong with the most recent charts release (16.10). This gets confusing since the most recent release (16.10) actually uses the 16.09 binary:
<img width="374" alt="Screen Shot 2019-10-08 at 5 10 20 PM" src="https://user-images.githubusercontent.com/4078018/66447013-5b162680-ea12-11e9-85d5-3a43d0f7809d.png">

It looks like this has been a longstanding issue (#268) the consequences of which is that our that our lockfile entries are not recognized and we always download the latest build in CI.

<img width="673" alt="Screen Shot 2019-10-08 at 9 30 53 PM" src="https://user-images.githubusercontent.com/4078018/66447155-f7402d80-ea12-11e9-8bca-7aaf0ef6c44e.png">
	
After removing the data vis pages and libraries, the site builds again: https://github.com/carbon-design-system/carbon-website/pull/471

**Comment by theiliad** [comment]
Fixed https://unpkg.com/browse/@carbon/charts@0.16.13/package.json

**Comment by vpicone** [comment]
@theiliad unfortunately the release issue was only a piece of the problem. charts-react is still failing static builds: https://github.com/carbon-design-system/carbon-website/pull/476/checks?check_run_id=254066126

**Comment by theiliad** [comment]
This was resolved last Wednesday, I believe we've had successful pushes to the website ever since
